language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build
  target-branch: master
  keep-history: true
  github-token: "$github_token"
  on:
    branch: develop
env:
  global:
  - secure: H5FwGipMymvrlmedxXKr+YZgyAeDkJCHGgB+TLF6IqV6F8JPjAisX2Sk2EbIM+5/V0EZc4z3OMN2iHsaV7cS+YOiahilevo8UNW+YqLEWPvYl79vVG+JQTnQs7mzVL0gZoWOxxish6h7Bl/VRiBJ5Qbt/WakHMLSrqdHj6TtNsgqoqnwt/n+sOAwxch9cBZdwK2lCZRknJqYuUEcdBrGAMMoKapaf83IKMw3E6QzY1eXL/arxY93xKkz486Sk5+O/VSkV7Sclta5ZzlCGEPQ7qs0XVG3y20nn3G7fnVINdfW+uwOpjJl9CEs5iJR0aooKk2Tpn5IYTXHdVI6hOojwboefRmRNhIfLcpfLExIVVkn55QFmT3TxTVwNUCr/hnV0yoRDU3X5lzfv8dBQp5i/8uL31cc4n65FlsjwjvqEOX7ERp+900q14VTKwFOZtakHaQdX/QtxBPEOXHLWDAG+tgFaUzv4Z9qkVc5Qhc4LPd87g6C2HXSTF4v8JcDI69WaMHr8nfJiqIElxW5YEmevvnlMOkG/XgVje4Lt95eQ4DSUxGqgA3ZAAek14EhdXvvsfio5U0gWjn/WNIx6gnslp6VawXvydpBMaeQaPPqG8x8a/lCLr2vgf+YpEQhtVn85Ot6dnu0IYvqx0k2BDOLGqXlcLv2WtQEvw1Drrq+CwU=
