language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build
  keep-history: true
  target-branch: master
  github-token: "$github_token"
  on:
    branch: develop
env:
  global:
  - secure: A35K0AxkABqPGJubWC03zjzvgtzvKCQ0OZ7yNCU4Abf2UKVvt/F5AkZzMMd6V75iD8wOcFG/O4GcYxdtYAHMrIjN6ADKMBNmMNfYB7sHhqcY+8/SqLNpi4yFboabp19zpki1Iu62WYga/YPT/Fes+NpEwGhmssY9W5308kBsK8u7Bx+d5vIsBN3WFWT2Fv4ydov+lwNpurN/93p9MZob5Lsc0OSgBBm6Qqcr82cocGBLfCPq31cm20Y2CnAMazz+MaG8kIyADNIie6SFYrfX+dzdrgJB8TgQYyd8L00gI0WxkA6yaB7+9M0P3FoL5gU1eAgfiPZfJa1u3KB0Qy6mchdwHPa6CF+31FN1HDhBZlwMtJk+3+ObgL6MDVblsrj2fmW3ALRpR5sOQdWrQaOvIGx7RN5QWBPd0StJEITQO1bVOZb2IfiaeeUlOBz0dl4hC0LWsrc/IcQ8QLi8/lGbqGuKkTkhIQ9Xufr9N+ORvuIAq462JkoC/MO5cxRKaM1ni4EZTCc0a1TNouLWmmmEXfW3Jx0sWxYuWxEebwP6o+77WPypxN1BDuQKoRffW/7uWic6HNpf6FmsVo/RMnbGoCtUc9X6TX7fPXqbYuVxgWXeY9bySf0+9ys0AeCRBXEuXNcMenQW/2XHDIeppzpy9jqESiOnQelgaDt5DWWHR/0=
